#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aws completion
source /usr/local/share/zsh/site-functions/_aws

# local utils
source "$HOME/.dotfiles/lib/chef_aliases.sh"
source "$HOME/.dotfiles/lib/git_utils.shlib"
