#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# aws completion
source /usr/local/bin/aws_zsh_completer.sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

export PATH="${HOME}/bin:${PATH}"

# go
export GOENV_ROOT="$HOME/.goenv"
export PATH="$GOENV_ROOT/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$GOROOT/bin:${RBENV_ROOT}/bin:$PATH"
export PATH="${PYENV_ROOT}/bin:$PATH:$GOPATH/bin"
eval "$(goenv init -)"
eval "$(pyenv init -)"

# powerline for zsh
source "/home/ejohanse/.pyenv/versions/3.7.3/lib/python3.7/site-packages/powerline/bindings/zsh/powerline.zsh"

# direnv
eval "$(direnv hook zsh)"

# rbenv
export RBENV_ROOT=~/devel/dotfiles/rbenv
eval "$(${RBENV_ROOT}/bin/rbenv init -)"

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/tmp/google-cloud-sdk/path.zsh.inc' ]; then . '/tmp/google-cloud-sdk/path.zsh.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/tmp/google-cloud-sdk/completion.zsh.inc' ]; then . '/tmp/google-cloud-sdk/completion.zsh.inc'; fi
